artindex/urls.py
from django.contrib import admin
from django.urls import path, include

from pieces.views import *
from pieces.urls import *

from schedule.views import *
from schedule.urls import *

from contacts.views import *
from schedule.urls import *


from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

##urlconf for Add_Edit & Pieces
urlpatterns += [
    path('', include('pieces.urls')),
    ]

##urlconf for schedule
urlpatterns += [
    path('', include('schedule.urls')),
]

##urlconf for contacts
urlpatterns += [
    path('', include('contacts.urls')),
]

##user auth pages
#urlpatterns += [
#    path('accounts/', include('django.contrib.auth.urls')),
#]


##static files
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path, include

from .views import *

app_name = 'contacts'

urlpatterns = [
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('contacts/new/', NewContactloadView.as_view(), name='new-contact'),
    path('contacts/<uuid:pk>/', ContactsDetailView.as_view(), name='detail'),
    path('contacts/<uuid:pk>/update', ContactsUpdateView.as_view(), name='contact-update'),
    path('contacts/<uuid:pk>/delete/', ContactsDeleteView.as_view(), name='delete'),
]

pieces/urls.py
from django.urls import path, include

from .views import *

app_name = 'artwork'

urlpatterns = [
    path('pieces/', PieceListView.as_view(), name='pieces'),
    path('pieces/new/', NewPieceUploadView.as_view(), name='new-upload'),
    path('pieces/<uuid:pk>/', PieceDetailView.as_view(), name="detail"),
    path('pieces/<uuid:pk>/update/', PieceUpdateView.as_view(), name='piece-update'),
    path('pieces/<uuid:pk>/delete/', PieceDeleteView.as_view(), name='delete'),
]

#urlpatterns += [
#    path('tutorial/', TutorialListView.as_view(), name='tutorial'),
#    path('tutorial/new/', NewPieceUploadView.as_view(), name='tutorial-upload')
#]

##test: https://www.geeksforgeeks.org/render-django-form-fields-manually/
urlpatterns += [
    path('home/', home_view, name="home"),
]

##upload dropzone
urlpatterns += [
    path('pieces/upload/', PieceOnlyUploadView.as_view(), name='piece-only'),
    path('pieces/upload-2/', PieceOnlyUploadView2.as_view(), name="piece-only-2"),
]

##collections
urlpatterns += [
    path('pieces/collection/', CollectionsListView.as_view(), name='my-collection'),
]

schedule/urls.py
from django.urls import path, include

from .views import CalendarView, event


##calendar

app_name = 'schedule'

urlpatterns = [
    path('schedule/calendar/', CalendarView.as_view(), name='calendar'),
    path('event/new/', event, name='event_new'),
    path('schedule/event/edit/<int:event_id>', event, name='event_edit'),
]

contacts/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect

import uuid

from shortuuidfield import ShortUUIDField

# Create your models here.
class Contact(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='unique uuid for contact')
    first_name = models.CharField(max_length=200)
    middle_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    job_title = models.CharField(max_length=200, null=True, blank=True)
    company = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone_number = models.CharField(max_length=200, null=True, blank=True)
    #date_of_birth = models.DateField(null=True, blank=True)
    #date_of_birth = models.DateField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True) #not working
    death_date = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=1000, null=True, blank=True)
    notes = models.TextField(max_length=1000, null=True, blank=True)

    CONTACT_TYPES = (
        ('Work', 'WORK'),
        ('Home', 'HOME'),
        ('Other', 'OTHER'),
        ('none', 'NONE'),
    )

    contact_types = models.CharField(
        max_length=5,
        choices=CONTACT_TYPES,
        blank=True,
        default='none',
        help_text='type',
    )

    contact_image = models.ImageField(upload_to='images/')

    class Meta:
        ordering = ['last_name', 'first_name']
    
    def get_absolute_url(self):
       return reverse('detail', args=[str(self.id)])

#    def __str__(self):
#        return '{0}, {1}'.format(self.id, self.first_name)

    def __str___(self):
        return '{0}, {1}'.format(self.first_name, self.last_name)
    
#    def get_absolute_url(self):
#        return HttpResponseRedirect(reverse('contacts-detail', args=[str(self.id)]))

contacts/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab
from crispy_forms.helper import FormHelper

from crispy_forms.layout import Submit, Layout, Div, Fieldset, Row, Column


from django import forms 
from .models import *



class NewContactUploadForm(forms.ModelForm):
    
    class Meta:
        model = Contact
        
        ##birth_date & death_date don't work##
        fields = [
            'first_name', 'middle_name', 'last_name',
            'job_title', 'company', 'email', 'phone_number',
            'bio', 'notes','contact_types', 'contact_image',
            'birth_date', 'death_date',
            ]
        
    ##form helper
    ##adapted from: https://django-crispy-forms.readthedocs.io/en/latest/crispy_tag_forms.html
    def __init__(self, *args, **kwargs):
        super(NewContactUploadForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id_new_upload_form'
        self.helper.form_class = 'uploadForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'upload_piece'
        self.helper.layout = Layout(
            Fieldset('contact_image',
                    Field('piece_upload', placeholder='Drag/Drop pieces here'),
            ),
            Fieldset(
            'first_name', 'middle_name', 'last_name',
            'job_title', 'company', 'email', 'phone_number',
            'bio', 'notes','contact_types',
            'birth_date', 'death_date',
            )
        ),
        Row(
                Column('first_name', css_class='form-group col-md-6 mb-0'),
                Column('middle_name', css_class='form-group col-md-4 mb-0'),
                Column('last_name', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
        Row(
                Column('job_title', css_class='form-group'),
                Column('company', css_class='form-group col-sm-2 mb-0'),
                css_class='form-row'
            ),

        self.helper.add_input(Submit('submit', 'Submit'))
    
    def clean_uploader(self):
        if not self.cleaned_data['uploader']:
            return User()
        return self.cleaned_data['uploader']

contacts/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect

from django.urls import reverse_lazy

from django.views import generic
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.http import HttpResponseRedirect

from django.urls import reverse_lazy

from django.views import generic
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django_filters.views import FilterView

from django_tables2 import SingleTableView
from django_tables2.views import SingleTableMixin

from .models import *
from .tables import ContactsTable
from .forms import *
from .filters import *

# Create your viws here.

        ##in use##

##contact specific detail views 
class ContactsDetailView(generic.DetailView):
    model = Contact
    template_name = 'contacts/contact_detail_working_copy.html'

##update contact
class ContactsUpdateView(generic.UpdateView):
    model = Contact
    fields = [
            'contact_image', 'first_name', 'middle_name', 'last_name',
            'job_title', 'company', 'email', 'phone_number',
            'bio', 'notes','contact_types',
            'birth_date', 'death_date',
            ]
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('contacts:contacts')


#delete contact
class ContactsDeleteView(DeleteView):
    model = Contact
    template_name_suffix = '_confirm_delete'
    success_url = reverse_lazy('contacts:contacts')

##list of contacts
class ContactsListView(LoginRequiredMixin, generic.ListView):
    table_class = ContactsTable
    model = Contact
    template_name = "contacts/contacts_list_final_working_copy.html"
    context_object_name = "contacts"

    filterset_class = FilterContacts


##new contact view
class NewContactloadView(TemplateView):
    form = NewContactUploadForm
    template_name = 'contacts/new_contact_working_copy.html'

    def post(self, request, *args, **kwargs):

        form = NewContactUploadForm(request.POST, request.FILES)

        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse_lazy('contacts:contacts'))

        context = self.get_context_data(form=form)
        return self.render_to_response(context)     

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


            ##end of in use##

contacts/templates/contacts/contact_detail_unformatted.html
{% extends "base_contacts.html" %}

{% block content %}

<h1>Contact</h1>

<p><strong>Author:</strong></a></p> <!-- author detail link not yet defined -->
<p><strong>First Name:</strong> {{ contact.first_name }}</p>
<p><strong>Last Name:</strong> {{ contact.last_name }}</p> 
<p><strong>Language:</strong></p>  
<p><strong>Genre:</strong> </p>
    
{% endblock %}

contacts/templates/contacts/contact_list_in_use.html
{% load static %}
{% load svg %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap 4 Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'contacts/contact_list362021.css' %}">
</head>

<body>
    <div class="container-fluid-1">
      <div class="row">
        <div class="col">
          {% block sidebar %}
         
          <ul class="sidebar-nav">
            <strong><h1>Art Index</h1></strong>
            <ul class="nav-artwork">{% svg 'nav-artwork' %}<a href="{% url 'artwork:pieces' %}">Artwork</a></ul>
            <br>
            <ul class='nav-locations'>{% svg 'nav-locations' %}<a href="">Location</a></ul>
            <br>
            <ul class='nav-exhibtions'>{% svg 'nav-exhibitions' %}<a href="">Exhibitions</a></ul>
            <br>
            <ul class='nav-schedule'>{% svg 'nav-schedule' %}<a href="{% url 'schedule:calendar' %}">Schedule</a></ul>
            <br>
            <ul class='nav-contacts'>{% svg 'nav-contacts' %}<a href="{% url 'contacts:contacts' %}">Contacts</a></ul>
            <br>
            <ul class='nav-income'>{% svg 'nav-income' %}<a href="">Income</a></ul>
            <br>
            <ul class='nav-reports'>{% svg 'nav-reports' %}<a href="">Reports</a></ul>
            <br>
            <ul class='nav-my-docs'>{% svg 'nav-my-docs' %}<a href="">My Docs</a></ul>
            <br>
            <ul class='nav-insights'>{% svg 'nav-insights' %}<a href="">Insights</a></ul>
          </ul>
          {% endblock %}
        </div>
        
        <div class="col">
          <div class="container-1">
            {% block header %}
            {% if contacts %}
            <div class="row">
              <div class="views">
                <h2><strong>Contacts</strong></h2>
                  <ul class="view-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-grid-1x2-fill" viewBox="0 0 16 16">
                      <path d="M0 1a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm9 0a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1V1zm0 9a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-5z"/>
                    </svg>
                  </ul>
                  <ul class="view-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-grid" viewBox="0 0 16 16">
                      <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
                    </svg>
                  </ul>
                  <ul class="view-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-grid-fill" viewBox="0 0 16 16">
                      <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zm8 0A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm-8 8A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm8 0A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3z"/>
                    </svg>
                  </ul>
              </div>
              <div class="col">
                <form method="get">
                  {{ filter.form|crispy }}
                </form>
              </div>
              <div class="new-contact">
                <h3><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                  <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                </svg>
                <a href="{% url 'contacts:new-contact' %}">New Contact</a></h3>
              </div>
            </div>
            <hr class="solid">
            {% endif %}
            {% endblock %}

            <div class="container-2">
              {% block content %}
              {% if contacts %}
              <div class="header-row">
                <ul class="contact-name"><strong>Name</strong></ul>
                <ul class="contact-email"><strong>Email</strong></ul>
                <ul class="contact-phone-number"><strong>Phone Number</strong></ul>
                <ul class="contact-title"><strong>Title</strong></ul>
                <ul class="contact-company"><strong>Company</strong></ul>
              {% for contact in contacts %}
              <div class="details-row">
                <li class="photo"><img src="{{ contact.contact_image.url }}" alt="Smilely face" width="50"></li>
                <li class="name-detail"><a href="{% url 'contacts:detail' contact.id %}">{{ contact.first_name }} {{ contact.last_name }}</a></li>
                <li class="email-detail"><a>{{ contact.email }}</a></li>
                <li class="phone-detail"><a>{{ contact.phone_number }}</a></li>
                <li class="title-detail"><a>{{ contact.title }}</a></li>
                <li class="company-detail"><a>{{ contact.company }}</a></li>
              </div>
                {% endfor %}
              {% endif %}
              {% endblock %}
            </div>
          </div>
        </div>  
      </div>
    </div>
</body>
</html>

contacts/templates/contacts/contact_list_unformatted.html
{% extends "base_contacts.html" %}
{% load static %}

{% block content %}
<h1><title>Pieces</title>
<a href="{% url 'contacts:new-contact' %}">Add Contact</a> 
</h1>

<body>
<div class="row">
  {% if contact_list %}
    {% for contact in contact_list %}
        <div class="col-md-8">
          <img src="{{ contact.contact_image.url}}" alt="Smiley face" width="50" height="50">
          {#<li>{{ contact.contact_image }}</li>#}
          </div>
        <div class="col-md-9">
            <a href="{{ contacts.get_absolute_url }}"> {{contact.first_name}} {{ contact.last_name }}</a>
            {# below now works #}
            <a href="{% url 'contacts:detail' contact.id %}"> {{contact.first_name}}</a>            
            </div>
        <div class="col-md-10">
            <title>email</title>
            <p>{{ contact.email }}</p>
          </div>
          <div class="col-md-9">
              <a href="{% url 'contacts:contact-update' contact.id %}">Edit</a>
              <a href="{% url 'contacts:delete' contact.id %}">Delete</a>
              <br>
          </div>
    {% endfor %}
  {% endif %}
</div>
</body>
{% endblock %}

contacts/templates/contacts/contact_list_working_copy.html
{% load static %}
{% load svg %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Art Index</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'contacts/contact_list362021.css' %}">
</head>

<body>
    <div class="container-fluid-1">
      <div class="row">
        <div class="col">
          {% block sidebar %}
         
          <ul class="sidebar-nav">
            <strong><h1>Art Index</h1></strong>
            <ul class="nav-artwork">{% svg 'nav-artwork' %}<a href="{% url 'artwork:pieces' %}">Artwork</a></ul>
            <br>
            <ul class='nav-locations'>{% svg 'nav-locations' %}<a href="">Location</a></ul>
            <br>
            <ul class='nav-exhibtions'>{% svg 'nav-exhibitions' %}<a href="">Exhibitions</a></ul>
            <br>
            <ul class='nav-schedule'>{% svg 'nav-schedule' %}<a href="{% url 'schedule:calendar' %}">Schedule</a></ul>
            <br>
            <ul class='nav-contacts'>{% svg 'nav-contacts' %}<a href="{% url 'contacts:contacts' %}">Contacts</a></ul>
            <br>
            <ul class='nav-income'>{% svg 'nav-income' %}<a href="">Income</a></ul>
            <br>
            <ul class='nav-reports'>{% svg 'nav-reports' %}<a href="">Reports</a></ul>
            <br>
            <ul class='nav-my-docs'>{% svg 'nav-my-docs' %}<a href="">My Docs</a></ul>
            <br>
            <ul class='nav-insights'>{% svg 'nav-insights' %}<a href="">Insights</a></ul>
          </ul>
          {% endblock %}
        </div>
        
        <div class="col">
          <div class="container-1">
            {% block header %}
            {% if contacts %}
            <div class="row">
              <div class="views">
                <h2><strong>Contacts</strong></h2>
                  <ul class="view-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-grid-1x2-fill" viewBox="0 0 16 16">
                      <path d="M0 1a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm9 0a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1V1zm0 9a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1v-5z"/>
                    </svg>
                  </ul>
                  <ul class="view-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-grid" viewBox="0 0 16 16">
                      <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
                    </svg>
                  </ul>
                  <ul class="view-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-grid-fill" viewBox="0 0 16 16">
                      <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zm8 0A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm-8 8A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm8 0A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3z"/>
                    </svg>
                  </ul>
              </div>
              <div class="col">
                <form method="get">
                  {{ filter.form|crispy }}
                </form>
              </div>
              <div class="new-contact">
                <h3><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                  <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                </svg>
                <a href="{% url 'contacts:new-contact' %}">New Contact</a></h3>
              </div>
            </div>
            <hr class="solid">
            {% endif %}
            {% endblock %}

            <div class="container-2">
              {% block content %}
              {% if contacts %}
              <div class="header-row">
                <ul class="contact-name"><strong>Name</strong></ul>
                <ul class="contact-email"><strong>Email</strong></ul>
                <ul class="contact-phone-number"><strong>Phone Number</strong></ul>
                <ul class="contact-title"><strong>Title</strong></ul>
                <ul class="contact-company"><strong>Company</strong></ul>
              {% for contact in contacts %}
              <div class="details-row">
                <li class="photo"><img src="{{ contact.contact_image.url }}" alt="Smilely face" width="50"></li>
                <li class="name-detail"><a href="{% url 'contacts:detail' contact.id %}">{{ contact.first_name }} {{ contact.last_name }}</a></li>
                <li class="email-detail"><a>{{ contact.email }}</a></li>
                <li class="phone-detail"><a>{{ contact.phone_number }}</a></li>
                <li class="title-detail"><a>{{ contact.title }}</a></li>
                <li class="company-detail"><a>{{ contact.company }}</a></li>
              </div>
                {% endfor %}
              {% endif %}
              {% endblock %}
            </div>
          </div>
        </div>  
      </div>
    </div>
</body>
</html>