artindex/urls.py
from django.contrib import admin
from django.urls import path, include

from pieces.views import *
from pieces.urls import *

from schedule.views import *
from schedule.urls import *

from contacts.views import *
from schedule.urls import *


from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

##urlconf for Add_Edit & Pieces
urlpatterns += [
    path('', include('pieces.urls')),
    ]

##urlconf for schedule
urlpatterns += [
    path('', include('schedule.urls')),
]

##urlconf for contacts
urlpatterns += [
    path('', include('contacts.urls')),
]

##user auth pages
#urlpatterns += [
#    path('accounts/', include('django.contrib.auth.urls')),
#]


##static files
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pieces/urls.py
from django.urls import path, include

from .views import *

app_name = 'artwork'

urlpatterns = [
    path('pieces/', PieceListView.as_view(), name='pieces'),
    path('pieces/new/', NewPieceUploadView.as_view(), name='new-upload'),
    path('pieces/<uuid:pk>/', PieceDetailView.as_view(), name="detail"),
    path('pieces/<uuid:pk>/update/', PieceUpdateView.as_view(), name='piece-update'),
    path('pieces/<uuid:pk>/delete/', PieceDeleteView.as_view(), name='delete'),
]

#urlpatterns += [
#    path('tutorial/', TutorialListView.as_view(), name='tutorial'),
#    path('tutorial/new/', NewPieceUploadView.as_view(), name='tutorial-upload')
#]

##test: https://www.geeksforgeeks.org/render-django-form-fields-manually/
urlpatterns += [
    path('home/', home_view, name="home"),
]

##upload dropzone
urlpatterns += [
    path('pieces/upload/', PieceOnlyUploadView.as_view(), name='piece-only'),
    path('pieces/upload-2/', PieceOnlyUploadView2.as_view(), name="piece-only-2"),
]

##collections
urlpatterns += [
    path('pieces/collection/', CollectionsListView.as_view(), name='my-collection'),
]

pieces/forms.py
from django import forms 
from django.contrib.auth.models import User

from .models import Piece, PieceInstance, Artist, NewPiece

##for crispy forms/form helper
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab
from crispy_forms.helper import FormHelper

from crispy_forms.layout import Submit, Layout, Div, Fieldset, Row, Column


#form for new img upload
#fields for title, img
class PieceOnly(forms.ModelForm):
    model = NewPiece
    fields = [
        'piece_upload', 'title'
    ]

class NewPieceInfo(forms.ModelForm):
    model = NewPiece
    fields = "__all__"



##in use
class NewUploadForm(forms.ModelForm):
    
    class Meta:
        model = NewPiece
        fields = [
            'piece_upload','artist', 'title',
            'description', 'types', 'medium',
            'subject_matter', 'location', 'date_of_upload',
            'visibility', 'width', 'height', 'depth', 'dim',
            'availability', 'price','tags',
            ]
    #tags
    #use "MultiValueField"

    ##form helper
    ##adapted from: https://django-crispy-forms.readthedocs.io/en/latest/crispy_tag_forms.html
    def __init__(self, *args, **kwargs):
        super(NewUploadForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id_new_upload_form'
        self.helper.form_class = 'uploadForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'upload_piece'
        self.helper.layout = Layout(
            Fieldset('Upload Piece Here',
                    Field('piece_upload', placeholder='Drag/Drop pieces here'),
            ),
            Fieldset('artist', 'title',
            'description', 'types', 'medium',
            'subject_matter', 'location', 'date_of_upload',
            'visibility', 'width', 'height', 'depth', 'dim',
            'availability', 'price', 'tags')
        ),
        Row(
                Column('availability', css_class='form-group col-md-6 mb-0'),
                Column('price', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
        Row(
                Column('height', css_class='form-group col-sm-2 mb-0'),
                Column('width', css_class='form-group col-sm-2 mb-0'),
                Column('depth', css_class="form-group col-sm-2 mb-0"),
                Column('dim', css_class="form-group col-sm-2 mb-0"),
                css_class='form-row'
            ),
        Row(
                Column('piece_upload', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
        )
        Row(
                Column('tags', css_class='form-group col-md-4 mb-0')
        )
        

        self.helper.add_input(Submit('submit', 'Submit'))
    
    def clean_uploader(self):
        if not self.cleaned_data['uploader']:
            return User()
        return self.cleaned_data['uploader']


##piece dropzone form
#adapted from:  https://github.com/jazzband/django-formtools/blob/master/docs/wizard.rst
class PieceUploadOnlyForm(forms.Form):
    piece_to_upload = forms.ImageField()






##one possible method of getting css & forms
class ContactForm(forms.Form):
      name = forms.CharField(required=False)
      email = forms.EmailField(label='Your email', widget=forms.TextInput(attrs={'class' : 'myemailclass'}))
      comment = forms.CharField(widget=forms.Textarea)


##tutorial: https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html#reusing-form-components
class ContactForm_Tutorial(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(),
        help_text='Write here your message!'
    )
    source = forms.CharField(       # A hidden input for internal use
        max_length=50,              # tell from which page the user sent the message
        widget=forms.HiddenInput()
    )

    def clean(self):
        cleaned_data = super(ContactForm_Tutorial, self).clean()
        name = cleaned_data.get('name')
        email = cleaned_data.get('email')
        message = cleaned_data.get('message')
        if not name and not email and not message:
            raise forms.ValidationError('You have to write something!')



##test: https://www.geeksforgeeks.org/render-django-form-fields-manually/
class InputForm(forms.Form): 
  
    first_name = forms.CharField(max_length = 200) 
    last_name = forms.CharField(max_length = 200) 
    roll_number = forms.IntegerField( 
                     help_text = "Enter 6 digit roll number"
                     ) 
    password = forms.CharField(widget = forms.PasswordInput())
    















#form for new piece info
#all additional data
class NewPieceCreateForm(forms.ModelForm):
    
    class Meta:
        model = NewPiece
        fields= [
            'description', 'types', 'medium',
            'subject_matter', 'location', 'date_of_upload',
            'visibility', 'width', 'height', 'depth', 'dim',
            'availability', 'price'
        ]


#form for new artists
class NewArtistCreateForm(forms.ModelForm):

    class Meta:
        model = Artist 
        fields = [
            'first_name', 'last_name',
            'artist_email', 'artist_phone'
        ]
 

pieces/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect

from django.urls import reverse_lazy

from django.views import generic
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin

from django_tables2 import SingleTableView

from django.utils.decorators import method_decorator

from .forms import *
from .tables import *
from .filters import *
from .models import *

# Create your views here.

##sidebar
def index(request):
    return render(request, 'index.html')


                ## pieces ##

##3 types of views for pieces lists

#Large:title, img large thumbnail w/ 3x3
class PiecesListLargeView(SingleTableView, FilterView):
    pass


##in use 

#Medium:
#single col
class PieceListView(LoginRequiredMixin, FilterView):
    table_class = PiecesTableMedium
    model = NewPiece
    template_name = "pieces/pieces_list_working_copy.html"
    #template_name = "pieces/pieces_try_in_use.html"    #up-to-date
    context_object_name = "pieces"
#    ordering = ["location"]
   # paginate_by = 5

    filterset_class = FilterTags

    def get_ordering_location(self):
        sort = self.request.GET.get('sort','location') #Order live feed events according to closest start date events at the top
        return sort
    

#class FilteredPieceListView2(SingleTableMixin, FilterView):
#    table_class = PiecesTableMedium
#    model = NewPiece
#    template_name = "pieces/pieces.html"

    #filterset_class = AvailabilityFilter

#Detail:
#single column 
class PieceDetailView(generic.DetailView):
    model = NewPiece
    template_name = 'pieces/piece_detail_working_copy.html'
    context_object_name = 'piece'


#update piece
#directs from collections url
#just can't change img
class PieceUpdateView(generic.UpdateView):
    model = NewPiece 
    fields = [
            'artist', 'title',
            'description', 'types', 'medium',
            'subject_matter', 'location', 'date_of_upload',
            'visibility', 'width', 'height', 'depth', 'dim',
            'availability', 'price','tags',
            ]
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('artwork:pieces')

#delete piece
class PieceDeleteView(DeleteView):
    model = NewPiece
    template_name_suffix = '_confirm_delete'
    success_url = reverse_lazy('artwork:pieces')



                    ##Add_Edit##


##version of this that works 

#uploading images, "Add Piece"
#link in painting list views
# upload/drag image field + submit btn
#creates new Painting Model
class NewPieceUploadView(SingleTableMixin, TemplateView):
    form = NewUploadForm
    template_name = 'pieces/add_piece_working_copy.html'
    #template_name = 'pieces/new_upload2_crispy_in_use.html'    #has dropbox

    def post(self, request, *args, **kwargs):

        form = NewUploadForm(request.POST, request.FILES)

        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse_lazy('artwork:pieces'))

        context = self.get_context_data(form=form)
        return self.render_to_response(context)     

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
        



##collections
class CollectionsListView(SingleTableMixin, generic.ListView):
    model = NewPiece
    queryset = NewPiece.objects.filter(location='NYC')
    template_name ='pieces/collections_working_copy.html'
    #paginate_by = 10
    context_object_name = 'collections'

    filterset = CollectionFilter

#    def get_queryset(self):
#        collection = NewPiece.objects.filter(uploader_id=self.request.user).values()
#        return render( 'pieces/collections_working_copy.html', {'collection': collection})
#        return NewPiece.objects.filter(uploader=self.request.user)



##end of in use##



##piece dropzone page
class PieceOnlyUploadView(TemplateView):
    form = PieceUploadOnlyForm
    template_name= 'pieces/piece_only_upload_in_use.html'
    #template_name= 'pieces/piece_only_upload_working_copy.html'    #not in use
    success_url = reverse_lazy('artwork:pieces')









##piece dropzone page2
#adapted from: https://www.existenceundefined.com/blog/programming/13/django-multiple-image-upload-with-dropzonejs
class PieceOnlyUploadView2(TemplateView):
    template_name = 'pieces/piece_only_upload2.html' 

    def post(self, request):
        body = request.POST.get('body', "")
        images = request.FILES.get('file[0]', None)

        if body or images:
            author = request.user
            post = SocialMediaPost()
            post.body = body
            post.author = author
            post.datetime_created = timezone.now()
            post.save()

            files = [request.FILES.get('file[%d]' % i) for i in range(0, len(request.FILES))]

            for image in files:
                photo = Photo(photo=image, user=request.user, obj_type='post', obj_id=post.pk)
                photo.save()

        return JsonResponse({'message': 'Post created'}, status=200)









##test
class NewPieceUploadView_1(TemplateView):
    form = ContactForm
    template_name = 'pieces/tutorial.html'

    def post(self, request, *args, **kwargs):

        form = ContactForm_Tutorial(request.POST, request.FILES)

        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse_lazy('artwork:tutorial-upload'))

        context = self.get_context_data(form=form)
        return self.render_to_response(context)     

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


##test
class TutorialListView(SingleTableMixin, FilterView):
    #table_class = PiecesTableMedium
    model = NewPiece_1
    template_name = "pieces/tutorial_list.html"
    context_object_name = "tutorials"


##test: https://www.geeksforgeeks.org/render-django-form-fields-manually/
def home_view(request): 
    context ={} 
    context['form']= InputForm() 
    return render(request, "pieces/home.html", context) 

pieces/templates/pieces/add_piece_working_copy.html
{% extends 'base_pieces_working_copy.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block header %}
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="{% static 'pieces/pieces_list3122021.css' %}">

<div class="container-1">
    <div class="row">
      <h2>Add Piece</h2>
        <div class="views">
        </div>
        <div class="tag-filter">
        </div>
      </div>
    <div class="row">
      {#<a href='#' onclick='overlay()'>Click here to show the overlay</a>#}
    </div>
      <hr class="solid">
      <div class="divider">
      </div>
      <br>
      <p></p>
{% endblock %}

{% block content %}
{% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'pieces/pieces_list3222021.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
    <script scr="/Volumes/Lexar/django/artindex/pieces/static/dropzone-5.7.0/dist/dropzone.js"></script>
    
  
    <div class="container-2" style="padding-top: 20px;">
      <h5><strong>Upload Image</strong></h5>
        <div class="container-4">
            <div class="col-md-12">
                <form action="/file-upload" class="dropzone">
                    {% csrf_token %}
                  <div class="fallback">
                      <input name="file" type="file" multiple />
                  </div>
                </form>
            </div>
        </div>
        <form method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div class="container-2">
                <div class="container-2">
                    <div class="row">
                        <div class="col">
                            <div class="form-group title">
                                    {{ form.title|as_crispy_field }}
                            </div>
                            <div class="form-group description">
                                    {{ form.description|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.artist|as_crispy_field }}
                            </div>
                            <p></p>
                            <div class="form-group">
                                    {{ form.types|as_crispy_field }}
                            </div>
                            <br>
                            <div class="form-group">
                                    {{ form.medium|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.subject_matter|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.location|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.date_of_upload|as_crispy_field }}
                            </div> 
                            <div class="form-group">  
                                {{ form.visibility|as_crispy_field }} 
                            </div>
                        </div>
            
                        <div class="col">
                            <div class="form-row">
                                <div class="form-group col-sm-2 mb-0">
                                    {{ form.height|as_crispy_field }}
                                </div>
                                <div class="form-group col-sm-2 mb-0">
                                    {{ form.width|as_crispy_field }}
                                </div>
                                <div class="form-group col-sm-2 mb-0">
                                    {{ form.depth|as_crispy_field }}
                                </div>
                                <div class="form-group col-sm-2 mb-0">
                                    {{ form.dim|as_crispy_field }}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6 mb-0">
                                    {{ form.availability|as_crispy_field }}
                                </div>
                                <div class="form-group col-md-6 mb-0">
                                    {{ form.price|as_crispy_field }}
                                </div> 
                            </div>  
                            <div class="form-row">
                                <div class="form-group col-md-6 mb-0">
                                    {{ form.tags|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
            <br>
            <br>
            <br>
            <button type="submit" class="btn btn-primary">Submit<a href="{% url 'artwork:pieces' %}"></a></button>
        </form>
        <br>
        <br>
    </div>
{% endblock %}

pieces/templates/pieces/new_upload2_crispy_in_use.html
{% extends 'pieces/pieces_try_in_use.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css">

{% load static %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
  <script scr="/Volumes/Lexar/django/artindex/pieces/static/dropzone-5.7.0/dist/dropzone.js"></script>

<div class="container-1">
    <div class="row">
        <div class="col" style="width: fit-content;"><h1>Add Piece</h1></div>
    </div>
    <hr class="solid">
    
    <div class="row">
      <div class="col-sm-1"></div>
      <div class="col-sm-1"></div>
      <div class="col-sm-1"></div>
      <div class="col-sm-1"></div>
      <div class="col-sm-1"></div>
    <br>
    <div class="container-2">
        <div class="container-4">
            <div class="col-md-12">
                <form action="/file-upload" class="dropzone">
                    {% csrf_token %}
                    <div class="fallback">
                        <input name="file" type="file" multiple />
                    </div>
                </form>
            </div>
        </div>  
    </div>
    {#<form id="id_new_upload_form" class="dropzone" method="POST" enctype="multipart/form-data">#}
    <form method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
        <div class="container-2">
            <div class="container-2">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                                {{ form.title|as_crispy_field }}
                        </div>
                        <div class="form-group">
                                {{ form.description|as_crispy_field }}
                        </div>
                        <div class="form-group">
                                {{ form.artist|as_crispy_field }}
                        </div>
                        <p></p>
                        <div class="form-group">
                                {{ form.types|as_crispy_field }}
                        </div>
                        <br>
                        <div class="form-group">
                                {{ form.medium|as_crispy_field }}
                        </div>
                        <div class="form-group">
                                {{ form.subject_matter|as_crispy_field }}
                        </div>
                        <div class="form-group">
                                {{ form.location|as_crispy_field }}
                        </div>
                        <div class="form-group">
                                {{ form.date_of_upload|as_crispy_field }}
                        </div> 
                        <div class="form-group">  
                            {{ form.visibility|as_crispy_field }} 
                        </div>
                    </div>
        
                    <div class="col">
                        <div class="form-row">
                            <div class="form-group col-sm-2 mb-0">
                                {{ form.height|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm-2 mb-0">
                                {{ form.width|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm-2 mb-0">
                                {{ form.depth|as_crispy_field }}
                            </div>
                            <div class="form-group col-sm-2 mb-0">
                                {{ form.dim|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6 mb-0">
                                {{ form.availability|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                {{ form.price|as_crispy_field }}
                            </div> 
                        </div>  
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit<a href="{% url 'artwork:pieces' %}"></a></button>
    </form>
</div>
{% endblock %}

pieces/templates/pieces/new_upload2_crispy_no_dropzone.html
{% extends 'pieces/pieces_try_working_copy.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block content %}
<div class="col-sm-10">
    <div class="container-1">
        <div class="row">
            <div class="col"><h1>Add ArtWork</h1></div>
            <div class="col"></div>
            <div class="col"></div>
        </div>    
    </div>
    <div class="container-1"> 
        {#<form id="id_new_upload_form" class="uploadForms" method="POST" enctype="multipart/form-data">#}
        <form method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div class="container-2">
                <div class="container-4">
                    <div class="form-row">
                        <div class="form-group col-md-4 mb-0">
                            {{ form.piece_upload|as_crispy_field }}
                        </div>
                    </div>    
                </div>
                <div class="container-2">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                    {{ form.title|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.description|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.artist|as_crispy_field }}
                            </div>
                            <p></p>
                            <div class="form-group">
                                    {{ form.types|as_crispy_field }}
                            </div>
                            <br>
                            <div class="form-group">
                                    {{ form.medium|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.subject_matter|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.location|as_crispy_field }}
                            </div>
                            <div class="form-group">
                                    {{ form.date_of_upload|as_crispy_field }}
                            </div> 
                            <div class="form-group">  
                                {{ form.visibility|as_crispy_field }} 
                            </div>
                        </div>
            
                        <div class="col">
                            <div class="form-row">
                                <div class="form-group col-sm-2 mb-0">
                                    {{ form.height|as_crispy_field }}
                                </div>
                                <div class="form-group col-sm-2 mb-0">
                                    {{ form.width|as_crispy_field }}
                                </div>
                                <div class="form-group col-sm-2 mb-0">
                                    {{ form.depth|as_crispy_field }}
                                </div>
                                <div class="form-group col-sm-2 mb-0">
                                    {{ form.dim|as_crispy_field }}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6 mb-0">
                                    {{ form.availability|as_crispy_field }}
                                </div>
                                <div class="form-group col-md-6 mb-0">
                                    {{ form.price|as_crispy_field }}
                                </div> 
                            </div>  
                            <div class="form-row">
                                <div class="form-group col-md-6 mb-0">
                                    {{ form.tags|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit<a href="{% url 'artwork:pieces' %}"></a></button>
        </form> 
    </div>
</div>
{% endblock %}

pieces/templates/pieces/new_upload_unformatted.html
{% extends "base_pieces.html" %}
{% load static %}


{% block content %}
<body>
<form method = "post" enctype="multipart/form-data"> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <button type="submit">Upload><a href="{% url 'artwork:pieces' %}"></a></button>
</form> 
</body>
{% endblock %} 
</html>

pieces/templates/pieces/piece_detail_unformatted.html
{% extends "base_pieces.html" %}
{% load static %}

{% block content %}
<body>
<h1>Piece</h1>

<p><strong>Author:</strong></a></p> <!-- author detail link not yet defined -->
<p><strong>First Name:</strong>{{ pieces.title }} </p>
<p><strong>Last Name:</strong></p> 
<p><strong>Language:</strong></p>  
<p><strong>Genre:</strong></p>
</body>    
{% endblock %}

pieces/templates/pieces/pieces.html
{% extends "base_pieces.html" %}
{% load static %}

{% block content %}
    <h1><title>Pieces</title>
    <a href="{% url 'artwork:new-upload' %}">"Add Piece"</a> 
    </h1>
<body>
<div class="row">
    {% if pieces %}
    <ul>

      {% for piece in pieces %}
          <div class="col-md-8">
            <img src="{{piece.piece_upload.url}}" alt="Smiley face" width="250" height="250">
            </div>
          <div class="col-md-9">
              <li>{{ piece.title }}</li>
              <li>{{ piece.description }}</li>
              </div>
          <div class="col-md-10">
              <li><p>Type: {{ piece.type }}</p></li>
              <li><p>Size: {{ piece.width }} x {{ piece.height }} x {{ piece.depth }}</p></li>
              <li><p>Subject: {{ piece.subject }}</p></li>
              <li><p>Location: {{ piece.location }}</p></li>
          </div>
      {% endfor %}
    {% endif %}
</div>
</body>
{% endblock %}

pieces/templates/pieces/pieces_standard.html
{% extends "base_pieces.html" %}

{% block content %}
{% load static %}
<div class='header-pieces'>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'pieces/pieces.css' %}">
    <h1><title>Pieces</title>
    <a href="{% url 'artwork:new-upload' %}">Add Piece</a> 
    </h1>
</div>

<body>
<hr class="solid">
<div class="row">
    {% if pieces %}
    <ul>
    <form method='get'>
        {{ filter.form.as_p }}
        <form method='get'>
            <input type='text' class="form-control-md-plaintext">
        </form></div>
    </form>

      {% for piece in pieces %}
          <div class="col-md-8">
            <img src="{{piece.piece_upload.url}}" alt="Smiley face" width="100" height="100">
            </div>
          <div class="col-md-9">
              <a href="{% url 'artwork:detail' piece.id %}">{{ piece.title }}</a>
              <li>{{ piece.description }}</li>
              </div>
          <div class="col-md-10">
              <li><p>Type: {{ piece.type }}</p></li>
              <li><p>Size: {{ piece.width }} x {{ piece.height }} x {{ piece.depth }}</p></li>
              <li><p>Subject: {{ piece.subject }}</p></li>
              <li><p>Location: {{ piece.location }}</p></li>
          </div>
          <div class="col-md-10">
              <a href="{% url 'artwork:piece-update' piece.id %}">Edit</a>
              <a href="{% url 'artwork:delete' piece.id %}">Delete</a>
          </div>
      {% endfor %}
    {% endif %}
</div>
</body>
{% endblock %}