artindex/urls.py
from django.contrib import admin
from django.urls import path, include

from pieces.views import *
from pieces.urls import *

from schedule.views import *
from schedule.urls import *

from contacts.views import *
from schedule.urls import *


from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

##urlconf for Add_Edit & Pieces
urlpatterns += [
    path('', include('pieces.urls')),
    ]

##urlconf for schedule
urlpatterns += [
    path('', include('schedule.urls')),
]

##urlconf for contacts
urlpatterns += [
    path('', include('contacts.urls')),
]

##user auth pages
#urlpatterns += [
#    path('accounts/', include('django.contrib.auth.urls')),
#]


##static files
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path, include

from .views import *

app_name = 'contacts'

urlpatterns = [
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('contacts/new/', NewContactloadView.as_view(), name='new-contact'),
    path('contacts/<uuid:pk>/', ContactsDetailView.as_view(), name='detail'),
    path('contacts/<uuid:pk>/update', ContactsUpdateView.as_view(), name='contact-update'),
    path('contacts/<uuid:pk>/delete/', ContactsDeleteView.as_view(), name='delete'),
]

pieces/urls.py
from django.urls import path, include

from .views import *

app_name = 'artwork'

urlpatterns = [
    path('pieces/', PieceListView.as_view(), name='pieces'),
    path('pieces/new/', NewPieceUploadView.as_view(), name='new-upload'),
    path('pieces/<uuid:pk>/', PieceDetailView.as_view(), name="detail"),
    path('pieces/<uuid:pk>/update/', PieceUpdateView.as_view(), name='piece-update'),
    path('pieces/<uuid:pk>/delete/', PieceDeleteView.as_view(), name='delete'),
]

#urlpatterns += [
#    path('tutorial/', TutorialListView.as_view(), name='tutorial'),
#    path('tutorial/new/', NewPieceUploadView.as_view(), name='tutorial-upload')
#]

##test: https://www.geeksforgeeks.org/render-django-form-fields-manually/
urlpatterns += [
    path('home/', home_view, name="home"),
]

##upload dropzone
urlpatterns += [
    path('pieces/upload/', PieceOnlyUploadView.as_view(), name='piece-only'),
    path('pieces/upload-2/', PieceOnlyUploadView2.as_view(), name="piece-only-2"),
]

##collections
urlpatterns += [
    path('pieces/collection/', CollectionsListView.as_view(), name='my-collection'),
]

schedule/urls.py
from django.urls import path, include

from .views import CalendarView, event


##calendar

app_name = 'schedule'

urlpatterns = [
    path('schedule/calendar/', CalendarView.as_view(), name='calendar'),
    path('event/new/', event, name='event_new'),
    path('schedule/event/edit/<int:event_id>', event, name='event_edit'),
]

templates/base.html
<!-- templates/base.html -->
{% load static %}
{% load svg %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Art Index</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'pieces/login.css' %}">
  <script>
    function overlay() {
	el = document.getElementById("overlay");
	el.style.visibility = (el.style.visibility == "visible") ? "hidden" : "visible";}
  </script>
</head>

<body>
    <div class="container-fluid-1">
      <div class="row">
        <div class="containter-1">
          {% block sidebar %}
         
          <ul class="sidebar-nav">
            <h1><strong>Art-Index</strong></h1>
            <ul class="nav-artwork">{% svg 'nav-artwork' %}<a href="{% url 'artwork:pieces' %}">Artwork</a></ul>
            <br>
            <ul class='nav-locations'>{% svg 'nav-locations' %}<a href="">Location</a></ul>
            <br>
            <ul class='nav-exhibtions'>{% svg 'nav-exhibitions' %}<a href="">Exhibitions</a></ul>
            <br>
            <ul class='nav-schedule'>{% svg 'nav-schedule' %}<a href="{% url 'schedule:calendar' %}">Schedule</a></ul>
            <br>
            <ul class='nav-contacts'>{% svg 'nav-contacts' %}<a href="{% url 'contacts:contacts' %}">Contacts</a></ul>
            <br>
            <ul class='nav-income'>{% svg 'nav-income' %}<a href="">Income</a></ul>
            <br>
            <ul class='nav-reports'>{% svg 'nav-reports' %}<a href="">Reports</a></ul>
            <br>
            <ul class='nav-my-docs'>{% svg 'nav-my-docs' %}<a href="">My Docs</a></ul>
            <br>
            <ul class='nav-insights'>{% svg 'nav-insights' %}<a href="">Insights</a></ul>
          </ul>
          {% endblock %}
        </div>
        
        <div class="col" id="wrapper-outer">
          <div class="container-2">
            {% block header %}
            {% endblock %}

            <div class="col" id="wrapper-inner">
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div> 
      </div>
    </div>
    <div class="clearer"></div>

    <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    
      {% block script %}
      {% endblock %}
</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}